# Generated by Django 4.0.1 on 2022-01-18 10:42

from django.db import migrations


def migrate_from_author_to_contibutors(apps, schema_migration):
    Blog = apps.get_model('blog', 'Blog')
    for blog in Blog.objects.all():
        blog.contributors.add(blog.author,
                              through_defaults={
                                  'contribution': 'Auteur principal'
                                  }
                              )


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcontributor_blog_contributors_alter_blog_author_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_from_author_to_contibutors)
    ]
